
# Configuración para el Rate Limiting en Netlify.
# Esto ayuda a proteger los endpoints sensibles de la aplicación contra abusos.

[[headers]]
  for = "/register"
  [headers.values]
    Rate-Limit-By = "ip"
    Rate-Limit-Window = "60" # 60 segundos (1 minuto)
    Rate-Limit-Limit = "10"  # 10 solicitudes por minuto por IP

[[headers]]
  for = "/scoring"
  [headers.values]
    Rate-Limit-By = "ip"
    Rate-Limit-Window = "60"
    Rate-Limit-Limit = "20"  # Un poco más alto para jurados

[[headers]]
  for = "/live"
  [headers.values]
    Rate-Limit-By = "ip"
    Rate-Limit-Window = "60"
    Rate-Limit-Limit = "5" # Más bajo para preguntas del público

[[headers]]
  for = "/survey"
  [headers.values]
    Rate-Limit-By = "ip"
    Rate-Limit-Window = "60"
    Rate-Limit-Limit = "5"

# Configuración de Cabeceras de Seguridad
[[headers]]
  for = "/*"
  [headers.values]
    # Forza la comunicación a través de HTTPS
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # Previene que el contenido sea interpretado como un tipo MIME diferente
    X-Content-Type-Options = "nosniff"
    # Previene que la página sea cargada en un iframe en otros sitios (previene clickjacking)
    X-Frame-Options = "DENY"
    # Controla la información de referencia que se envía con las solicitudes
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Política de Seguridad de Contenido (CSP)
    # Es conservadora para permitir que la app funcione con sus dependencias externas.
    Content-Security-Policy = "default-src 'self' https://*.firebaseio.com https://*.firebasestorage.googleapis.com https://*.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.youtube.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' wss://*.firebaseio.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com; frame-src 'self' https://www.youtube.com https://www.canva.com;"
    # Controla el acceso a APIs y características del navegador
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
